# Generated by Django 5.1.2 on 2024-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_user_remove_artifact_file_artifact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
