# Generated by Django 5.1.2 on 2024-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_artifact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
